my_string = "hello World, my name is Andres Osorio"
# Metodos
print(dir(my_string))
print('upper -> ', my_string.upper())
print('lower -> ', my_string.lower())
print('swapcase -> ', my_string.swapcase())
print('capitalize -> ', my_string.capitalize())
print('replace -> ', my_string.replace('hello', 'bye'))
print('replace > upper -> ', my_string.replace('hello', 'bye').upper())
print('count -> ', my_string.count('l'))
print('count -> ', my_string.count('Andres'))
print('count -> ', my_string.count(' '))
print('count -> ', my_string.count(''))
print('startswith -> ', my_string.startswith('Andres'))
print('startswith -> ', my_string.startswith('hello'))
print('endswith -> ', my_string.endswith('Andres'))
print('endswith -> ', my_string.endswith('rio'))
print('split -> ', my_string.split(' '))
print('split -> ', my_string.split('o'))
print('lower > split -> ', my_string.lower().split('o'))
print('find -> ', my_string.find('o'))
print('find -> ', my_string.find('A'))
print('find -> ', my_string.find('l'))
print('len -> ', len(my_string))
print('index -> ', my_string.index('is'))
print('[n] -> ', my_string[0])
print('[n] -> ', my_string[16])
print('[n] -> ', my_string[8])
print('[n] -> ', my_string[-22])
print('[n] -> ', my_string[-5])
print('[n] -> ', my_string[-15])
print('[n] -> ', my_string[-24])
print('isnumeric -> ', my_string.isnumeric())
print('isalpha -> ', my_string.isalpha())
print('Concatenate + ->'+my_string)
print('Concatenate , ->', my_string)
print(f'Concatenate f -> {my_string}')
print('Concatenate format -> {0}'.format(my_string))
my_string = "123456"
print('isnumeric -> ', my_string.isnumeric())
my_string = "abcdefg"
print('isalpha -> ', my_string.isalpha())
